### ISSUE TITLE
Restructure the connector to allow for extendability

### ISSUE THREAD

**Issue by nickdenardis** [waynestate/waynestate-api-php#4]
Examples:
- https://bitbucket.org/mailchimp/mailchimp-api-php/src/03ae0dba64d1a902fb4d76004ef12c8391ededc8/src/Mailchimp.php?at=master
- https://github.com/cosenary/Instagram-PHP-API/blob/master/src/Instagram.php
- https://bitbucket.org/mailchimp/mandrill-api-php/src/9f336b08ea148c80db3b694f3dc737cd4f414e19/src/Mandrill.php?at=master
- https://github.com/dropbox/dropbox-sdk-php (not ideal structure)
- https://github.com/twilio/twilio-php/blob/master/Services/Twilio.php
- https://github.com/toin0u/DigitalOceanV2/blob/master/src/DigitalOceanV2.php
- https://github.com/zendesk/zendesk_api_client_php/blob/master/src/Zendesk/API/Client.php
- https://github.com/stripe/stripe-php (not ideal structure)

**Comment by robertvrabel** [comment]
Going to close this since it been a few years and we haven't had a need to change anything

**Comment by nickdenardis** [comment]
👍
